# Generated by Django 5.0.2 on 2024-02-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genepro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mirna',
        ),
    ]
